nombre = input("¿Cómo te llamas?")
print("Hola " + nombre)
pregunta = input("¿Cómo conoces a Máx?")
print("Ya veo...")
pregunta1 = input("¿Te cae bien Máx?")
print("A mi también, " "jajajaja")
pregunta2 = input("¿Deberíamos de hacer algo en contra de el?")
print("Concuerdo contigo!")
input ()